# Generated by Django 4.1.4 on 2023-04-10 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=50)),
                ('postagem', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=100)),
                ('rastreio', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('cartao', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 46, 28, 925574))),
                ('data_att', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaCorreios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('servico', models.CharField(max_length=50)),
            ],
        ),
    ]
