# Generated by Django 4.1.4 on 2023-04-10 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_envio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 48, 26, 32915)),
        ),
    ]
