# Generated by Django 4.1.4 on 2023-04-10 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0013_alter_envio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
