# Generated by Django 4.1.4 on 2023-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0014_alter_envio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='rastreio',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
