# Generated by Django 4.1.4 on 2023-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0015_alter_envio_rastreio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='rastreio',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
