# Generated by Django 4.1.4 on 2023-04-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0018_setores_alter_recebidos_departamento'),
        ('envios', '0016_alter_envio_rastreio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostagem',
            name='setor',
        ),
        migrations.AddField(
            model_name='codigopostagem',
            name='departamento',
            field=models.ForeignKey(default=-3, on_delete=django.db.models.deletion.DO_NOTHING, to='envios.envio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigopostagem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envios.etiquetacorreios'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recebimentos.setores'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envios.etiquetacorreios'),
        ),
    ]
