# Generated by Django 4.1.4 on 2023-04-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0018_setores_alter_recebidos_departamento'),
        ('envios', '0017_remove_codigopostagem_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostagem',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recebimentos.setores'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envios.codigopostagem'),
        ),
    ]
