# Generated by Django 4.1.4 on 2023-04-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0019_alter_recebidos_departamento'),
        ('envios', '0019_alter_codigopostagem_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='cartao',
        ),
        migrations.AddField(
            model_name='envio',
            name='postagem',
            field=models.ForeignKey(default=-3, on_delete=django.db.models.deletion.PROTECT, to='envios.codigopostagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigopostagem',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recebimentos.setores'),
        ),
        migrations.AlterField(
            model_name='codigopostagem',
            name='postagem',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codigopostagem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.etiquetacorreios'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recebimentos.setores'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.etiquetacorreios'),
        ),
    ]
