# Generated by Django 4.1.4 on 2023-05-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0023_alter_setores_departamento'),
        ('envios', '0020_remove_envio_cartao_envio_postagem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codigopostagem',
            unique_together={('departamento', 'servico')},
        ),
    ]
