# Generated by Django 4.1.4 on 2023-05-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficios',
            old_name='observação',
            new_name='observacao',
        ),
    ]
