# Generated by Django 4.1.4 on 2023-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0003_alter_beneficios_brinde_alter_beneficios_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='brinde',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='saude',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='va',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='vt',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
