# Generated by Django 4.1.4 on 2023-05-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0004_alter_beneficios_brinde_alter_beneficios_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='brinde',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='saude',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='va',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='vt',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
