# Generated by Django 4.1.4 on 2023-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0006_alter_beneficios_observacao_alter_beneficios_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficios',
            name='data_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
