# Generated by Django 4.1.4 on 2023-04-10 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recebidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('remetente', models.CharField(max_length=100, null=True)),
                ('cep_remetente', models.CharField(max_length=100, null=True)),
                ('rastreio', models.CharField(max_length=100, null=True)),
                ('ar_anexa', models.CharField(max_length=100, null=True)),
                ('departamento', models.CharField(max_length=100, null=True)),
                ('data_recebimento', models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 46, 28, 925574))),
                ('data_att', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('forma_entrega', models.CharField(max_length=100, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
