# Generated by Django 4.1.4 on 2023-04-10 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0013_alter_recebidos_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebidos',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
