# Generated by Django 4.1.4 on 2023-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0014_alter_recebidos_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebidos',
            name='rastreio',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
