# Generated by Django 4.1.4 on 2023-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0015_alter_recebidos_rastreio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebidos',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
