# Generated by Django 4.1.4 on 2023-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0016_recebidos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebidos',
            name='rastreio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
