# Generated by Django 4.1.4 on 2023-04-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0018_setores_alter_recebidos_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebidos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recebimentos.setores'),
        ),
    ]
