# Generated by Django 4.1.4 on 2023-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0020_alter_setores_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setores',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
